# Abordagem 2

Usando a abordagem 2 para gerar templates com foco em templates positivos e negativos. Uma possível aplicação seria testar a capacidade linguística *Vocabullary* com o teste **MFT**.

As etapas desta abordagem são:

1. Rankear as palavras das instâncias completas
2. Quebrar as instâncias em sentenças
3. Filtrar as sentenças que contêm ao menos uma das palavras mais bem rankeadas na etapa anterior
4. Rankear as palavras de cada sentença
5. Filtrar as sentenças com palavras relevantes (adjetivos ou verbos)
6. Classificar as sentenças usando o *Oráculo*
7. Substituir as palavras relevantes por máscaras

In [1]:
%config Completer.use_jedi = False
import sys
sys.path.append('../')

## Carregando o dataset, o modelo alvo e os modelos auxiliares

In [2]:
import pandas as pd
pd.set_option('display.max_colwidth', None)

imdb_df = pd.read_csv('./data/imdb_sampled/data-1000samples.csv')
imdb_df.head(5)

,label,text,words
0,0,"Here's example number 87,358 of Hollywood's anti-Biblical bias, so typical of them.<br /><br />Early on, Ray Liotta's wife has did and women are being interviewed for the position of housekeeper. The first interviewee is an old-fashioned-looking (dress, mannerisms, speech) who immediately lays down here strict rules, stating that ""there will be two hours of Bible study ever day.""<br /><br />This is said, of course, to make it sound like reading the Bible is the worse punishment you could ever inflict on someone, especially a kid. Once again, the Bible is equated with stuffy, mean-spirited people. That woman, of course, is dismissed immediately.<br /><br />Naturally, the liberal black woman (Whoopi Goldberg - who else?) is the one who is hired and, voilà, saves the day! <br /><br />Yawn.",127
1,0,"I don't know about the real Cobb but I got the distinct impression that the filmmakers' aim was to try to soften his jagged edges and reputation, not give us a true portrait of the man himself. In the movie, besides a few racist remarks, he's shown to be just another hard-nosed, cantakerous old coot (he's so full of life!) with a heart of gold(more or less). This is also the worst acting I've seen T.L.Jones do(he brings nothing new or subtle to his stereotyped character). He just doesn't flesh out Cobb in a way that pulls me into the movie. Not for one minute did I forget that it was Tommy Lee Jones on the screen pretending to be Ty Cobb. Robert Wuhl didnt impress either. The ""comedic"" elements in this movie were just distracting and didnt ring true at all. A bloody waste of time, it is",149
2,0,"Reba is a very dumb show. You can predict pretty much anything that's about to happen. Barbra Jean is just too stupid. It's like she's not even a character. A show like this should at least have SOMEONE who resembles a real-life person. I guess Barbra Jean represents a retarded person. Keira or whatever her name is, Reba, Brock, they're all stupid! Keira is like the smartest person on the show, and she's still stupid. EVERYONE IS STUPID! That's my opinion on Reba. Since I have said all I can say about this show, I'll just take up the next few lines of text by saying what I am currently saying right now and do it until there's 10 lines. There. Reba gets 2/10.",124
3,1,"""One Crazy Summer"" is the funniest, craziest (not necessarily the best), movie I have ever seen.<br /><br />Just when one crazy scene is done, another emerges. It never lets you rest. Just one thing after another. The soundtrack is great. The songs are the right ones for the scenes.<br /><br />It is also a clean movie. Little that is dirty in it.<br /><br />Of course, it has the story of the guys you wouldn't trust with your lunch money, taking up a challenge, and winning over people with more resources. Who'd want to see it if they failed? There is a serious side, in that parents and children do not live up to each others' dreams. One should always have an open mind, and weigh all the options. This applies both to parents and children. In ""One Crazy Summer"", the parents are wrong. This is not always the case.",149
4,0,"""A young man, recently engaged to be married, is the victim of a traffic accident and dies as a result of his injuries. His father, desperate to revive his son, agrees to let a scientist friend try his experimental soul transmigration process to save him. After the young man returns to life, the father and fiancée notice a dark and violent change in the young man's behavior, leading them to believe something went horribly wrong in the revival process,"" according to the DVD sleeve's synopsis.<br /><br />At one point, Edward Norris (as Philip Bennett) is asked, ""What do you think this is, Boys Town?"" Mr. Norris should know, since he was in ""Boys Town"". ""The Man with Two Lives "" is more like ""Black Friday"" minus Karloff and Lugosi. You do the math. This film might have been a contender, with a re-worked script; it does feature an intriguing final act. After a tepid ""shoot out"", hang in for the drama to pick up with a well-played scene between star Norris and pursuing detective Addison Richards (as George Bradley).<br /><br />**** The Man with Two Lives (1942) Phil Rosen ~ Edward Norris, Eleanor Lawson, Addison Richards",196

In [3]:
import re
import numpy as np
from torch.nn.functional import softmax
from transformers import AutoTokenizer, AutoModelForSequenceClassification

def pre_proccess(text):
    text = text.lower()
    text = re.sub('["\',!-.:-@0-9/]()', ' ', text)
    return text

# Wrapper to adapt output format
class SentimentAnalisysModelWrapper:
    def __init__(self, model, tokenizer):
        self.model = model
        self.tokenizer = tokenizer
        
    def __predict(self, text_input):
        text_preprocessed = pre_proccess(text_input)
        tokenized = self.tokenizer(text_preprocessed, padding=True, truncation=True, max_length=512, 
                                    add_special_tokens = True, return_tensors="pt")
        
        tensor_logits = self.model(**tokenized)
        prob = softmax(tensor_logits[0]).detach().numpy()
        pred = np.argmax(prob)
        
        return pred, prob
    
    def predict_label(self, text_inputs):
        return self.predict(text_inputs)[0]
        
    def predict_proba(self, text_inputs):
        return self.predict(text_inputs)[1]
        
    def predict(self, text_inputs):
        if isinstance(text_inputs, str):
            text_inputs = [text_inputs]
        
        preds = []
        probs = []

        for text_input in text_inputs:
            pred, prob = self.__predict(text_input)
            preds.append(pred)
            probs.append(prob[0])

        return np.array(preds), np.array(probs) # ([0, 1], [[0.99, 0.01], [0.03, 0.97]])

# Auxiliar function to load and wrap a model from Hugging Face
def load_model(model_name):
    print(f'Loading model {model_name}...')
    model = AutoModelForSequenceClassification.from_pretrained(model_name)
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    
    return SentimentAnalisysModelWrapper(model, tokenizer)

# Hugging Face hosted model names 
imdb_models = {
    'bert': 'textattack/bert-base-uncased-imdb', 
    'albert': 'textattack/albert-base-v2-imdb', 
    'distilbert': 'textattack/distilbert-base-uncased-imdb', 
    'roberta': 'textattack/roberta-base-imdb', 
    'xlnet': 'textattack/xlnet-base-cased-imdb'
}

In [4]:
m1 = load_model(imdb_models['albert'])
m2 = load_model(imdb_models['distilbert'])
m3 = load_model(imdb_models['roberta'])
m4 = load_model(imdb_models['xlnet'])

# Models to be used as oracle
models = [m1, m2, m3, m4]
# Target model
model = load_model(imdb_models['bert'])

Loading model textattack/albert-base-v2-imdb...
Loading model textattack/distilbert-base-uncased-imdb...
Loading model textattack/roberta-base-imdb...

Some weights of the model checkpoint at textattack/roberta-base-imdb were not used when initializing RobertaForSequenceClassification: ['roberta.pooler.dense.weight', 'roberta.pooler.dense.bias']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

Loading model textattack/xlnet-base-cased-imdb...
Loading model textattack/bert-base-uncased-imdb...

# Gerando os templates
O método de rankeamento das palavras usado no PosNegTemplateGenerator é o Replace-1 Score

In [5]:
from template_generator.tasks.sentiment_analisys import PosNegTemplateGeneratorApp2

tg = PosNegTemplateGeneratorApp2(model, models)

### Número inicial de instâncias: 5

In [6]:
# Sampling instances
np.random.seed(220)
n_instances = 5
df_sampled = imdb_df.sample(n_instances)

instances = [x for x in df_sampled['text'].values]

In [7]:
templates = tg.generate_templates(instances)

Ranking words using Replace-1 Score...

<ipython-input-3-3748665271fa>:23: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  prob = softmax(tensor_logits[0]).detach().numpy()

Converting texts to sentences...
:: 31 sentences were generated.
Filtering instances by contaning ranked words...
:: 13 sentences remaining.
Ranking words using Replace-1 Score...
:: Word ranking done.
Filtering instances by relevant words...
:: 0 sentences remaining.
Predicting inputs...
:: Sentence predictions done.

#### Tempo de execução para 5 instâncias: 6m 19.8s

In [8]:
df = tg.to_dataframe()
df

Empty DataFrame
Columns: [label, original_text, masked_text, template_text]
Index: []

In [9]:
tg.lexicons

{'pos_adj': [], 'neg_adj': []}

### Número inicial de instâncias: 100

In [10]:
# Using all 100 instances
instances = [x for x in imdb_df['text'].values]

In [11]:
templates = tg.generate_templates(instances)

Ranking words using Replace-1 Score...

<ipython-input-3-3748665271fa>:23: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  prob = softmax(tensor_logits[0]).detach().numpy()

Converting texts to sentences...
:: 7973 sentences were generated.
Filtering instances by contaning ranked words...
:: 3497 sentences remaining.
Ranking words using Replace-1 Score...
:: Word ranking done.
Filtering instances by relevant words...
:: 72 sentences remaining.
Predicting inputs...
:: Sentence predictions done.

#### Tempo de execução para 100 instâncias: 132m 12.5s

In [12]:
df = tg.to_dataframe()
df

,label,original_text,masked_text,template_text
0,0,"That woman, of course, is dismissed immediately.<br /><br />Naturally, the liberal black woman (Whoopi Goldberg - who else?)","That woman , of course , is dismissed {mask} < br / > < br / > Naturally , the {mask} black woman ( Whoopi Goldberg - who else ? )","That woman , of course , is dismissed {neg_adj} < br / > < br / > Naturally , the {pos_adj} black woman ( Whoopi Goldberg - who else ? )"
1,0,"I laughed and giggled enough times through the movie so I cannot say with hand on my heart that it was rubbish.<br /><br />It's completely different, this and Epic Movie (Epic Movie sucked bad..","I laughed and giggled enough times through the movie so I can not say with hand on my heart that it was {mask} < br / > < br / > It 's completely different , this and Epic Movie ( Epic Movie sucked {mask} ..","I laughed and giggled enough times through the movie so I can not say with hand on my heart that it was {neg_adj} < br / > < br / > It 's completely different , this and Epic Movie ( Epic Movie sucked {neg_adj} .."
2,1,Fantastic performances from the two leads and a great look to the film that gave it a real authentic feel.,{mask} performances from the two leads and a great look to the film that gave it a real {mask} feel .,{pos_adj} performances from the two leads and a great look to the film that gave it a real {pos_adj} feel .
3,1,It very excellent none the less.,It very {mask} none the {mask} .,It very {pos_adj} none the {neg_adj} .
4,0,"The only positive I can think is there are semi-good special effects and camera work, and the musical score sounds OK.<br /><br />Overall this a ridiculous family fantasy that will only appeal to those who expect nothing from a movie.<br /><br />My rating: 1/2 out of ****.","The {mask} positive I can think is there are semi-good special effects and camera work , and the musical score sounds OK. < br / > < br / > Overall this a {mask} family fantasy that will only appeal to those who expect nothing from a movie. < br / > < br / > My rating : 1/2 out of * * * * .","The {pos_adj} positive I can think is there are semi-good special effects and camera work , and the musical score sounds OK. < br / > < br / > Overall this a {neg_adj} family fantasy that will only appeal to those who expect nothing from a movie. < br / > < br / > My rating : 1/2 out of * * * * ."
...,...,...,...,...
67,0,"The animation is sloppy, the story lines resemble Saturday morning cartoons, and not all of the original voices are there.","The animation is {mask} , the story lines {mask} Saturday morning cartoons , and not all of the original voices are there .","The animation is {neg_adj} , the story lines {neg_adj} Saturday morning cartoons , and not all of the original voices are there ."
68,1,"This movie is definitely not typical Eastwood, but surely worth watching.","This movie is definitely not {mask} Eastwood , but surely {mask} watching .","This movie is definitely not {neg_adj} Eastwood , but surely {pos_adj} watching ."
69,0,"It is very very obvious that this movie was on the bottom of the programming totem poll, the move is so low budget.","It is very very {mask} that this movie was on the bottom of the programming totem poll , the move is so {mask} budget .","It is very very {neg_adj} that this movie was on the bottom of the programming totem poll , the move is so {neg_adj} budget ."
70,1,Danson is outstanding as the title character and edward fox makes a wonderful villain.,Danson is {mask} as the title character and edward fox makes a {mask} villain .,Danson is {pos_adj} as the title character and edward fox makes a {pos_adj} villain .
71,0,"The only positive in the movie is the presence of some talented actors who did not help much text to explode their talents Finally.., iwant to know your comment about this movie guys... is it bad or what?","The {mask} positive in the movie is the presence of some talented actors who did not help much text to explode their talents Finally .. , iwant to know your comment about this movie guys ... is it {mask} or what ?","The {pos_adj} positive in the movie is the presence of some talented actors who did not help much text to explode their talents Finally .. , iwant to know your comment about this movie guys ... is it {neg_adj} or what ?"

In [13]:
tg.lexicons

{'pos_adj': ['excellent',
  'brilliant',
  'sweet',
  'tight',
  'clean',
  'believable',
  'Incredible',
  'great',
  'light-hearted',
  'wonderful',
  'solid',
  'minor',
  'inventive',
  'musical',
  'best',
  'eerie',
  'finest',
  'decent',
  'saddest',
  'commendable',
  'authentic',
  'liberal',
  'sci-fi',
  'remarkable',
  'only',
  'attractive',
  'enjoyable',
  'bearable',
  'tragic',
  'asinine',
  'vivid',
  'satisfied',
  'short',
  'awesome',
  'direct-to-video',
  'independent',
  'constant',
  'Fantastic',
  'noir',
  'episodic',
  'entertaining',
  'favourite',
  'heartfelt.',
  'good',
  'multi-millionaire',
  'present.',
  'hard',
  'positive',
  'flawless',
  'worth',
  'outstanding',
  'incredible',
  'amazing',
  'happy',
  'respectable'],
 'neg_adj': ['awful',
  'stereotypical',
  'i.e',
  'immediately.',
  'worst',
  'campy',
  'horrendous',
  'appealing',
  'main',
  'little',
  'underdeveloped.',
  'tedious',
  'homoerotic',
  'opposite',
  'acted',
  'unoriginal',
  'creepier',
  'poor',
  'rubbish.',
  'uncomfortable',
  'twisted',
  'sloppy',
  'strange',
  'bad',
  'better',
  'terrible',
  'dull',
  'disappointed',
  'first',
  'tiresome.',
  'predictable',
  'last',
  'typical',
  'bad-movie',
  'laughable',
  'interesting',
  'least',
  'unconvincing',
  'low',
  'most',
  'pretty',
  'alien',
  'many',
  'initial',
  'crappy',
  'big',
  'flawed',
  'anti-climactic',
  'less',
  'ridiculous',
  "ripoff's.",
  'funny',
  'obvious',
  'resemble',
  'clichéd']}

# Usando os templates gerados pelo TemplateGenerator no CheckList

In [14]:
from checklist.editor import Editor
from checklist.test_suite import TestSuite
from checklist.test_types import MFT

In [15]:
lexicons = tg.lexicons
templates = tg.template_texts
masked = tg.masked_texts
labels = [sent.prediction.label for sent in tg.sentences]

editor = Editor()
editor.add_lexicon('pos_adj', lexicons['pos_adj'])
editor.add_lexicon('neg_adj', lexicons['neg_adj'])

suite = TestSuite()

In [16]:
for template, label, i in zip(templates, labels, range(len(templates))):
    t = editor.template(template, remove_duplicates=True, labels=int(label))

    suite.add(MFT(
        data=t.data,
        labels=label,
        capability="Vocabullary", 
        name=f"Test: MFT with vocabullary - template{i+1}",
        description="Checking if the model can handle vocabullary"))

In [17]:
suite.run(model.predict, overwrite=True)
suite.save('./suites/posneg-approach2.suite')

Running Test: MFT with vocabullary - template1
Predicting 3025 examples

<ipython-input-3-3748665271fa>:23: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  prob = softmax(tensor_logits[0]).detach().numpy()

Running Test: MFT with vocabullary - template2
Predicting 55 examples
Running Test: MFT with vocabullary - template3
Predicting 55 examples
Running Test: MFT with vocabullary - template4
Predicting 3025 examples
Running Test: MFT with vocabullary - template5
Predicting 3025 examples
Running Test: MFT with vocabullary - template6
Predicting 3025 examples
Running Test: MFT with vocabullary - template7
Predicting 55 examples
Running Test: MFT with vocabullary - template8
Predicting 55 examples
Running Test: MFT with vocabullary - template9
Predicting 55 examples
Running Test: MFT with vocabullary - template10
Predicting 3025 examples
Running Test: MFT with vocabullary - template11
Predicting 3025 examples
Running Test: MFT with vocabullary - template12
Predicting 55 examples
Running Test: MFT with vocabullary - template13
Predicting 3025 examples
Running Test: MFT with vocabullary - template14
Predicting 55 examples
Running Test: MFT with vocabullary - template15
Predicting 3025 examples
Running Test: MFT with vocabullary - template16
Predicting 55 examples
Running Test: MFT with vocabullary - template17
Predicting 3025 examples
Running Test: MFT with vocabullary - template18
Predicting 55 examples
Running Test: MFT with vocabullary - template19
Predicting 55 examples
Running Test: MFT with vocabullary - template20
Predicting 3025 examples
Running Test: MFT with vocabullary - template21
Predicting 55 examples
Running Test: MFT with vocabullary - template22
Predicting 55 examples
Running Test: MFT with vocabullary - template23
Predicting 3025 examples
Running Test: MFT with vocabullary - template24
Predicting 55 examples
Running Test: MFT with vocabullary - template25
Predicting 3025 examples
Running Test: MFT with vocabullary - template26
Predicting 3025 examples
Running Test: MFT with vocabullary - template27
Predicting 3025 examples
Running Test: MFT with vocabullary - template28
Predicting 55 examples
Running Test: MFT with vocabullary - template29
Predicting 55 examples
Running Test: MFT with vocabullary - template30
Predicting 3025 examples
Running Test: MFT with vocabullary - template31
Predicting 55 examples
Running Test: MFT with vocabullary - template32
Predicting 3025 examples
Running Test: MFT with vocabullary - template33
Predicting 55 examples
Running Test: MFT with vocabullary - template34
Predicting 3025 examples
Running Test: MFT with vocabullary - template35
Predicting 55 examples
Running Test: MFT with vocabullary - template36
Predicting 55 examples
Running Test: MFT with vocabullary - template37
Predicting 55 examples
Running Test: MFT with vocabullary - template38
Predicting 3025 examples
Running Test: MFT with vocabullary - template39
Predicting 3025 examples
Running Test: MFT with vocabullary - template40
Predicting 3025 examples
Running Test: MFT with vocabullary - template41
Predicting 3025 examples
Running Test: MFT with vocabullary - template42
Predicting 55 examples
Running Test: MFT with vocabullary - template43
Predicting 55 examples
Running Test: MFT with vocabullary - template44
Predicting 55 examples
Running Test: MFT with vocabullary - template45
Predicting 55 examples
Running Test: MFT with vocabullary - template46
Predicting 55 examples
Running Test: MFT with vocabullary - template47
Predicting 55 examples
Running Test: MFT with vocabullary - template48
Predicting 3025 examples
Running Test: MFT with vocabullary - template49
Predicting 3025 examples
Running Test: MFT with vocabullary - template50
Predicting 55 examples
Running Test: MFT with vocabullary - template51
Predicting 55 examples
Running Test: MFT with vocabullary - template52
Predicting 55 examples
Running Test: MFT with vocabullary - template53
Predicting 3025 examples
Running Test: MFT with vocabullary - template54
Predicting 55 examples
Running Test: MFT with vocabullary - template55
Predicting 3025 examples
Running Test: MFT with vocabullary - template56
Predicting 55 examples
Running Test: MFT with vocabullary - template57
Predicting 55 examples
Running Test: MFT with vocabullary - template58
Predicting 55 examples
Running Test: MFT with vocabullary - template59
Predicting 55 examples
Running Test: MFT with vocabullary - template60
Predicting 3025 examples
Running Test: MFT with vocabullary - template61
Predicting 3025 examples
Running Test: MFT with vocabullary - template62
Predicting 55 examples
Running Test: MFT with vocabullary - template63
Predicting 3025 examples
Running Test: MFT with vocabullary - template64
Predicting 55 examples
Running Test: MFT with vocabullary - template65
Predicting 3025 examples
Running Test: MFT with vocabullary - template66
Predicting 3025 examples
Running Test: MFT with vocabullary - template67
Predicting 55 examples
Running Test: MFT with vocabullary - template68
Predicting 55 examples
Running Test: MFT with vocabullary - template69
Predicting 3025 examples
Running Test: MFT with vocabullary - template70
Predicting 55 examples
Running Test: MFT with vocabullary - template71
Predicting 55 examples
Running Test: MFT with vocabullary - template72
Predicting 3025 examples

In [19]:
suite.summary()

Vocabullary

Test: MFT with vocabullary - template1
Test cases:      3025
Fails (rate):    2871 (94.9%)

Example fails:
0.9 That woman , of course , is dismissed typical < br / > < br / > Naturally , the minor black woman ( Whoopi Goldberg - who else ? )
----
1.0 That woman , of course , is dismissed unoriginal < br / > < br / > Naturally , the saddest black woman ( Whoopi Goldberg - who else ? )
----
0.8 That woman , of course , is dismissed campy < br / > < br / > Naturally , the musical black woman ( Whoopi Goldberg - who else ? )
----


Test: MFT with vocabullary - template2
Test cases:      55
Fails (rate):    4 (7.3%)

Example fails:
0.7 I laughed and giggled enough times through the movie so I can not say with hand on my heart that it was ripoff's. < br / > < br / > It 's completely different , this and Epic Movie ( Epic Movie sucked ripoff's. ..
----
0.8 I laughed and giggled enough times through the movie so I can not say with hand on my heart that it was horrendous < br / > < br / > It 's completely different , this and Epic Movie ( Epic Movie sucked horrendous ..
----
0.7 I laughed and giggled enough times through the movie so I can not say with hand on my heart that it was funny < br / > < br / > It 's completely different , this and Epic Movie ( Epic Movie sucked funny ..
----


Test: MFT with vocabullary - template3
Test cases:      55
Fails (rate):    0 (0.0%)


Test: MFT with vocabullary - template4
Test cases:      3025
Fails (rate):    550 (18.2%)

Example fails:
0.0 It very great none the i.e .
----
0.0 It very happy none the appealing .
----
0.5 It very worth none the resemble .
----


Test: MFT with vocabullary - template5
Test cases:      3025
Fails (rate):    1788 (59.1%)

Example fails:
1.0 The enjoyable positive I can think is there are semi-good special effects and camera work , and the musical score sounds OK. < br / > < br / > Overall this a pretty family fantasy that will only appeal to those who expect nothing from a movie. < br / > < br / > My rating : 1/2 out of * * * * .
----
0.9 The excellent positive I can think is there are semi-good special effects and camera work , and the musical score sounds OK. < br / > < br / > Overall this a campy family fantasy that will only appeal to those who expect nothing from a movie. < br / > < br / > My rating : 1/2 out of * * * * .
----
1.0 The liberal positive I can think is there are semi-good special effects and camera work , and the musical score sounds OK. < br / > < br / > Overall this a typical family fantasy that will only appeal to those who expect nothing from a movie. < br / > < br / > My rating : 1/2 out of * * * * .
----


Test: MFT with vocabullary - template6
Test cases:      3025
Fails (rate):    1267 (41.9%)

Example fails:
1.0 This is just a production that really missed the mark , a real low for Austen fans. < br / > < br / > The brilliant serviceable version is the one with odd duck ( perfect for the role ) Sylvestra La Touzel ( despite the very very gay Henry Crawford - he 's just appealing ) .
----
0.9 This is just a production that really missed the mark , a real low for Austen fans. < br / > < br / > The positive serviceable version is the one with odd duck ( perfect for the role ) Sylvestra La Touzel ( despite the very very gay Henry Crawford - he 's just first ) .
----
1.0 This is just a production that really missed the mark , a real low for Austen fans. < br / > < br / > The Incredible serviceable version is the one with odd duck ( perfect for the role ) Sylvestra La Touzel ( despite the very very gay Henry Crawford - he 's just homoerotic ) .
----


Test: MFT with vocabullary - template7
Test cases:      55
Fails (rate):    32 (58.2%)

Example fails:
1.0 The heartfelt. thing heartfelt. about this movie is the artwork on the promotion poster by H. R. Geiger .
----
0.6 The only thing only about this movie is the artwork on the promotion poster by H. R. Geiger .
----
1.0 The authentic thing authentic about this movie is the artwork on the promotion poster by H. R. Geiger .
----


Test: MFT with vocabullary - template8
Test cases:      55
Fails (rate):    32 (58.2%)

Example fails:
0.0 In fact you could say Thriller is sloppy then most horror movies with that sloppy second sparkling eye .
----
0.0 In fact you could say Thriller is low then most horror movies with that low second sparkling eye .
----
0.1 In fact you could say Thriller is campy then most horror movies with that campy second sparkling eye .
----


Test: MFT with vocabullary - template9
Test cases:      55
Fails (rate):    27 (49.1%)

Example fails:
1.0 Yes `` Coneheads '' was better but kind of had a one joke premise and `` Black Sheep '' I agreed with the critics is one of the better movies ever made .
----
1.0 Yes `` Coneheads '' was typical but kind of had a one joke premise and `` Black Sheep '' I agreed with the critics is one of the typical movies ever made .
----
1.0 Yes `` Coneheads '' was homoerotic but kind of had a one joke premise and `` Black Sheep '' I agreed with the critics is one of the homoerotic movies ever made .
----


Test: MFT with vocabullary - template10
Test cases:      3025
Fails (rate):    1131 (37.4%)

Example fails:
1.0 After a while of very twisted dialogue and very `` arty '' type moody scenes I was starting to realise why we were the sweet people there .
----
1.0 After a while of very many dialogue and very `` arty '' type moody scenes I was starting to realise why we were the heartfelt. people there .
----
1.0 After a while of very interesting dialogue and very `` arty '' type moody scenes I was starting to realise why we were the excellent people there .
----


Test: MFT with vocabullary - template11
Test cases:      3025
Fails (rate):    2263 (74.8%)

Example fails:
0.0 The camera work is ripoff's. solid .
----
0.2 The camera work is typical happy .
----
0.0 The camera work is horrendous present. .
----


Test: MFT with vocabullary - template12
Test cases:      55
Fails (rate):    22 (40.0%)

Example fails:
0.9 What saves this film from becoming a Hallmark spectacle and debacle of the usual sort , whenever films about serial killers are concerned , is the direction , which is a double-edged sword ; director Scott L. Flynn sheds focus enough upon the b-actors not to let their flaws shine through too much , but at the same times created a truly typical and typical view of the American police through the King-angle .
----
1.0 What saves this film from becoming a Hallmark spectacle and debacle of the usual sort , whenever films about serial killers are concerned , is the direction , which is a double-edged sword ; director Scott L. Flynn sheds focus enough upon the b-actors not to let their flaws shine through too much , but at the same times created a truly main and main view of the American police through the King-angle .
----
1.0 What saves this film from becoming a Hallmark spectacle and debacle of the usual sort , whenever films about serial killers are concerned , is the direction , which is a double-edged sword ; director Scott L. Flynn sheds focus enough upon the b-actors not to let their flaws shine through too much , but at the same times created a truly twisted and twisted view of the American police through the King-angle .
----


Test: MFT with vocabullary - template13
Test cases:      3025
Fails (rate):    48 (1.6%)

Example fails:
0.5 For those who grew up in the eighties , it is an artful piece of nostalgia and a episodic story well dull and produced .
----
0.0 For those who grew up in the eighties , it is an artful piece of nostalgia and a minor story well laughable and produced .
----
0.0 For those who grew up in the eighties , it is an artful piece of nostalgia and a inventive story well laughable and produced .
----


Test: MFT with vocabullary - template14
Test cases:      55
Fails (rate):    46 (83.6%)

Example fails:
1.0 The sci-fi thing that made it sci-fi was the two bottles of wine that I downed during the course of the flick .
----
0.6 The enjoyable thing that made it enjoyable was the two bottles of wine that I downed during the course of the flick .
----
0.9 The favourite thing that made it favourite was the two bottles of wine that I downed during the course of the flick .
----


Test: MFT with vocabullary - template15
Test cases:      3025
Fails (rate):    0 (0.0%)


Test: MFT with vocabullary - template16
Test cases:      55
Fails (rate):    4 (7.3%)

Example fails:
0.8 ? < br / > < br / > To me it 's nothing more than a bad Hollywood war movie in German. < br / > < br / > This movie is so pretty on so pretty levels .
----
1.0 ? < br / > < br / > To me it 's nothing more than a bad Hollywood war movie in German. < br / > < br / > This movie is so appealing on so appealing levels .
----
0.9 ? < br / > < br / > To me it 's nothing more than a bad Hollywood war movie in German. < br / > < br / > This movie is so funny on so funny levels .
----


Test: MFT with vocabullary - template17
Test cases:      3025
Fails (rate):    1069 (35.3%)

Example fails:
0.0 An clean abandon house , interesting characters , gore and a terrible plot .
----
0.0 An constant abandon house , interesting characters , gore and a unconvincing plot .
----
0.0 An noir abandon house , interesting characters , gore and a dull plot .
----


Test: MFT with vocabullary - template18
Test cases:      55
Fails (rate):    7 (12.7%)

Example fails:
0.6 Plot - good resemble idea but truly resemble development .
----
0.9 Plot - good typical idea but truly typical development .
----
0.9 Plot - good twisted idea but truly twisted development .
----


Test: MFT with vocabullary - template19
Test cases:      55
Fails (rate):    17 (30.9%)

Example fails:
0.1 The directing is episodic , the casting is episodic ( though I would 've loved to have seen a little more of Aaron Lustig ( from Y & R fame ) , who played Paul Shaffer ) .
----
0.0 The directing is sci-fi , the casting is sci-fi ( though I would 've loved to have seen a little more of Aaron Lustig ( from Y & R fame ) , who played Paul Shaffer ) .
----
0.1 The directing is respectable , the casting is respectable ( though I would 've loved to have seen a little more of Aaron Lustig ( from Y & R fame ) , who played Paul Shaffer ) .
----


Test: MFT with vocabullary - template20
Test cases:      3025
Fails (rate):    2747 (90.8%)

Example fails:
0.0 One- Roebuck 's Leno is commendable , but his stage presence ( typical .
----
0.3 One- Roebuck 's Leno is independent , but his stage presence ( strange .
----
0.0 One- Roebuck 's Leno is outstanding , but his stage presence ( unoriginal .
----


Test: MFT with vocabullary - template21
Test cases:      55
Fails (rate):    24 (43.6%)

Example fails:
0.0 John Clarke plays the clubs arch nemesis - he is trying to take the club over and turn it into a `` Poker Machine Slum '' Jack and the other club members band together to try and save the club with terrible terrible twists and turns and Jacks eventual redemption .
----
0.5 John Clarke plays the clubs arch nemesis - he is trying to take the club over and turn it into a `` Poker Machine Slum '' Jack and the other club members band together to try and save the club with low low twists and turns and Jacks eventual redemption .
----
0.0 John Clarke plays the clubs arch nemesis - he is trying to take the club over and turn it into a `` Poker Machine Slum '' Jack and the other club members band together to try and save the club with dull dull twists and turns and Jacks eventual redemption .
----


Test: MFT with vocabullary - template22
Test cases:      55
Fails (rate):    18 (32.7%)

Example fails:
1.0 - The character development is pretty - The characters that appear in the movie are so pretty you would < br / > < br / > recognize them in your average comic book .
----
1.0 - The character development is strange - The characters that appear in the movie are so strange you would < br / > < br / > recognize them in your average comic book .
----
1.0 - The character development is immediately. - The characters that appear in the movie are so immediately. you would < br / > < br / > recognize them in your average comic book .
----


Test: MFT with vocabullary - template23
Test cases:      3025
Fails (rate):    2094 (69.2%)

Example fails:
0.0 It 's like every one of them has an laughable -- just so minor , like watching anti-matter collide .
----
0.0 It 's like every one of them has an clichéd -- just so good , like watching anti-matter collide .
----
0.0 It 's like every one of them has an worst -- just so vivid , like watching anti-matter collide .
----


Test: MFT with vocabullary - template24
Test cases:      55
Fails (rate):    30 (54.5%)

Example fails:
0.9 Heart of Darkness , a short novel written by Joseph Conrad about greed , corruption , and traveling through Africa was , to say the resemble , a resemble read .
----
1.0 Heart of Darkness , a short novel written by Joseph Conrad about greed , corruption , and traveling through Africa was , to say the appealing , a appealing read .
----
0.9 Heart of Darkness , a short novel written by Joseph Conrad about greed , corruption , and traveling through Africa was , to say the creepier , a creepier read .
----


Test: MFT with vocabullary - template25
Test cases:      3025
Fails (rate):    56 (1.9%)

Example fails:
0.0 laughable people said this was a musical movie with Hoffman delivering a great performance .
----
0.1 crappy people said this was a independent movie with Hoffman delivering a great performance .
----
0.0 laughable people said this was a only movie with Hoffman delivering a great performance .
----


Test: MFT with vocabullary - template26
Test cases:      3025
Fails (rate):    2655 (87.8%)

Example fails:
0.0 This to me is a shame , Stupid comedies open on at least 2000 screens but real satisfied drams as this & many others open in only a few. < br / > < br / > By the way there are some very resemble lines regarding certain situations. < br / > < br / > Ratings : * * * 1/2 ( out of 4 ) 95 points ( out of 100 ) IMDb 9 ( out of 10 )
----
0.0 This to me is a shame , Stupid comedies open on at least 2000 screens but real remarkable drams as this & many others open in only a few. < br / > < br / > By the way there are some very homoerotic lines regarding certain situations. < br / > < br / > Ratings : * * * 1/2 ( out of 4 ) 95 points ( out of 100 ) IMDb 9 ( out of 10 )
----
0.0 This to me is a shame , Stupid comedies open on at least 2000 screens but real authentic drams as this & many others open in only a few. < br / > < br / > By the way there are some very underdeveloped. lines regarding certain situations. < br / > < br / > Ratings : * * * 1/2 ( out of 4 ) 95 points ( out of 100 ) IMDb 9 ( out of 10 )
----


Test: MFT with vocabullary - template27
Test cases:      3025
Fails (rate):    1043 (34.5%)

Example fails:
0.7 The plot relies on a series of incredibly improbable coincidences ; there 's a hefty dose of conspiracy theory which would be much more palatable if we did n't know that Seagal takes it all literally ; and once again , underdeveloped. wonderful Seagal tells us all about the evils of The Rich. < br / > < br / > Seagal 's survival relies , as usual , on the fact that Bad Guys never fire their guns from out of arm 's reach , and always like to give a little `` I 'm gon na kill you '' speech before blowing a man 's head off. < br / > < br / > Watch this one right after the even-worse * Fire Down Below * and note how the carpet in Keenen Ivory Wayans 's apartment is more flammable than a big puddle of gasoline. < br / > < br / > Oh , and watch in the final fight scene for the Incredible Disappearing Forehead Wound , which is probably the most entertaining thing in the film .
----
0.8 The plot relies on a series of incredibly improbable coincidences ; there 's a hefty dose of conspiracy theory which would be much more palatable if we did n't know that Seagal takes it all literally ; and once again , sloppy vivid Seagal tells us all about the evils of The Rich. < br / > < br / > Seagal 's survival relies , as usual , on the fact that Bad Guys never fire their guns from out of arm 's reach , and always like to give a little `` I 'm gon na kill you '' speech before blowing a man 's head off. < br / > < br / > Watch this one right after the even-worse * Fire Down Below * and note how the carpet in Keenen Ivory Wayans 's apartment is more flammable than a big puddle of gasoline. < br / > < br / > Oh , and watch in the final fight scene for the Incredible Disappearing Forehead Wound , which is probably the most entertaining thing in the film .
----
1.0 The plot relies on a series of incredibly improbable coincidences ; there 's a hefty dose of conspiracy theory which would be much more palatable if we did n't know that Seagal takes it all literally ; and once again , interesting finest Seagal tells us all about the evils of The Rich. < br / > < br / > Seagal 's survival relies , as usual , on the fact that Bad Guys never fire their guns from out of arm 's reach , and always like to give a little `` I 'm gon na kill you '' speech before blowing a man 's head off. < br / > < br / > Watch this one right after the even-worse * Fire Down Below * and note how the carpet in Keenen Ivory Wayans 's apartment is more flammable than a big puddle of gasoline. < br / > < br / > Oh , and watch in the final fight scene for the Incredible Disappearing Forehead Wound , which is probably the most entertaining thing in the film .
----


Test: MFT with vocabullary - template28
Test cases:      55
Fails (rate):    2 (3.6%)

Example fails:
0.1 That 's why I 'm minor that Jacobi 's Hamlet is the minor performance I 've seen by an actor .
----
0.0 That 's why I 'm asinine that Jacobi 's Hamlet is the asinine performance I 've seen by an actor .
----


Test: MFT with vocabullary - template29
Test cases:      55
Fails (rate):    26 (47.3%)

Example fails:
0.5 The entire cast from the previous movie & series is constant < br / > < br / > These kind of movies are constant to watch in the MovieTheater cause the whole audience is crying with laughter , especially at the terrorist part that was damn disgusting .
----
0.5 The entire cast from the previous movie & series is positive < br / > < br / > These kind of movies are positive to watch in the MovieTheater cause the whole audience is crying with laughter , especially at the terrorist part that was damn disgusting .
----
0.4 The entire cast from the previous movie & series is happy < br / > < br / > These kind of movies are happy to watch in the MovieTheater cause the whole audience is crying with laughter , especially at the terrorist part that was damn disgusting .
----


Test: MFT with vocabullary - template30
Test cases:      3025
Fails (rate):    2600 (86.0%)

Example fails:
1.0 At i.e John Krasinksi showed some enthusiasm. < br / > < br / > Yes , John Krasinski is the only reason I rented this flick , and its the believable real reason worth watching .
----
1.0 At twisted John Krasinksi showed some enthusiasm. < br / > < br / > Yes , John Krasinski is the only reason I rented this flick , and its the awesome real reason worth watching .
----
1.0 At strange John Krasinksi showed some enthusiasm. < br / > < br / > Yes , John Krasinski is the only reason I rented this flick , and its the bearable real reason worth watching .
----


Test: MFT with vocabullary - template31
Test cases:      55
Fails (rate):    6 (10.9%)

Example fails:
0.4 I actually heard about this movie many years ago , but never knew what it was called , so I 'm happy to have found it by accident. < br / > < br / > These Andersons were nothing Fantastic of amazing in their writing , the execution of the completely Fantastic and realistic-looking models , the quality of acting , etc. < br / > < br / > I do n't think it looks dated at all .
----

# Carregando suite de teste

In [18]:
from checklist.test_suite import TestSuite
suite = TestSuite.from_file('./suites/posneg-approach2.suite')

suite.visual_summary_table()

Please wait as we prepare the table data...

SuiteSummarizer(stats={'npassed': 0, 'nfailed': 0, 'nfiltered': 0}, test_infos=[{'name': 'Test: MFT with vocab…